/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import clases.Cliente;
import vistas.Menu;
import javax.swing.JOptionPane;
import clases.Directorio;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.Set;
import java.util.TreeMap;

/**
 *
 * @author AsRock
 */
public class JIntFrBuscarCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form JIntFrBorrarCliente
     */
    public JIntFrBuscarCliente() {
        initComponents();
        this.setLocation(10, 15);
        jbtBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lupa3.jpg")));

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jTextTelefono = new javax.swing.JTextField();
        jbtBuscar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jbtSalir = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jTextCiudad = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextApellido = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextNombre = new javax.swing.JTextField();
        jTextDni = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextDireccion = new javax.swing.JTextField();
        jlbIImagenLupa = new javax.swing.JLabel();

        setClosable(true);
        setPreferredSize(new java.awt.Dimension(400, 400));

        jLabel7.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 24)); // NOI18N
        jLabel7.setText("Buscar Cliente");

        jTextTelefono.setBackground(new java.awt.Color(204, 204, 204));
        jTextTelefono.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextTelefonoFocusLost(evt);
            }
        });
        jTextTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextTelefonoActionPerformed(evt);
            }
        });

        jbtBuscar.setText("Buscar");
        jbtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtBuscarActionPerformed(evt);
            }
        });

        jLabel8.setText("Telefono:");

        jbtSalir.setText("Salir");
        jbtSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSalirActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Resultados :", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 12))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setToolTipText("");
        jPanel1.setName(""); // NOI18N

        jTextCiudad.setEditable(false);
        jTextCiudad.setBackground(new java.awt.Color(102, 102, 102));
        jTextCiudad.setForeground(new java.awt.Color(255, 255, 255));
        jTextCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCiudadActionPerformed(evt);
            }
        });

        jLabel6.setText("Ciudad:");

        jLabel5.setText("Direccion:");

        jTextApellido.setEditable(false);
        jTextApellido.setBackground(new java.awt.Color(102, 102, 102));
        jTextApellido.setForeground(new java.awt.Color(255, 255, 255));

        jLabel3.setText("Apellido:");

        jLabel2.setText("Nombre:");

        jTextNombre.setEditable(false);
        jTextNombre.setBackground(new java.awt.Color(102, 102, 102));
        jTextNombre.setForeground(new java.awt.Color(255, 255, 255));

        jTextDni.setEditable(false);
        jTextDni.setBackground(new java.awt.Color(102, 102, 102));
        jTextDni.setForeground(new java.awt.Color(255, 255, 255));
        jTextDni.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextDniFocusLost(evt);
            }
        });

        jLabel1.setText("D.N.I.:");

        jTextDireccion.setEditable(false);
        jTextDireccion.setBackground(new java.awt.Color(102, 102, 102));
        jTextDireccion.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextApellido)
                            .addComponent(jTextDireccion)
                            .addComponent(jTextNombre)
                            .addComponent(jTextDni, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(79, 79, 79))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbtBuscar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jlbIImagenLupa, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jbtSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)
                        .addComponent(jbtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jlbIImagenLupa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtSalir)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextTelefonoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextTelefonoFocusLost

        try{

            long valorJText = Long.parseLong(jTextTelefono.getText());          //<---Si no Ingreso un numero que maneje el error . Hago qie el telefono se almacene en una variable int ya que si no es un numero lo que viene, que maneje ele error  (aunque el telefono lo almaceno como un string en el mapa)

        }catch(NumberFormatException e){

            if (!jTextTelefono.getText().equals("")){
                JOptionPane.showMessageDialog(this, "El campo 'Telefono:' solo admite Numeros");
                jTextTelefono.requestFocus();
            }
        }
    }//GEN-LAST:event_jTextTelefonoFocusLost

    private void jTextTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextTelefonoActionPerformed
    //---Metodo Limpiar Text Flies----------------------------------------------
    private void limpairCamposDeTexto(){
    
        jTextDni.setText("");
        jTextNombre.setText("");
        jTextApellido.setText("");
        jTextDireccion.setText("");
        jTextCiudad.setText("");
        jTextTelefono.setText("");
    }
    
    //--------------------------------------------------------------------------
    
    
    
    

    //---------Llamo a Buscar Cliente ---- Pansando el telefono-------------
        
        /*  ENUNCIADO: 
            En base al nro de teléfono retorna el 
            Cliente asociado al mismo.
        
            Retorna: Cliente
        */
    private void jbtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtBuscarActionPerformed
        
        
        if(jTextTelefono.getText().equals("")){
            
            JOptionPane.showMessageDialog(this,"No puede dejar el campo 'Telefono' sin completar");
            jTextTelefono.requestFocus();
        
        }else{  
        
            try{

                int valorJText = Integer.parseInt(jTextTelefono.getText());          //<---Si no Ingreso un numero que maneje el error . Hago qie el telefono se almacene en una variable int ya que si no es un numero lo que viene, que maneje ele error  (aunque el telefono lo almaceno como un string en el mapa)


                Cliente clienteRetornado = Menu.getDirectorio().buscarCliente(jTextTelefono.getText());

                if ( clienteRetornado != null){

                    jTextDni.setText(clienteRetornado.getDni()+"");
                    jTextNombre.setText(clienteRetornado.getNombre());
                    jTextApellido.setText(clienteRetornado.getApellido());
                    jTextDireccion.setText(clienteRetornado.getDireccion());
                    jTextCiudad.setText(clienteRetornado.getCiudad());

                }else{

                  String telefonoBuscado = jTextTelefono.getText();
                  limpairCamposDeTexto();
                  JOptionPane.showMessageDialog(null,"No se ha encontrado un cliente con el telefono: " + telefonoBuscado );
                  jTextTelefono.requestFocus();

                }

                        
                }catch(NumberFormatException e){

                    if (!jTextTelefono.getText().equals("")){
                     //   JOptionPane.showMessageDialog(this, "El campo 'Telefono:' solo admite Numeros");
                        jTextTelefono.requestFocus();
                    }
                }
           
        
        
        }    
            
            
    }//GEN-LAST:event_jbtBuscarActionPerformed

    private void jbtSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbtSalirActionPerformed

    private void jTextDniFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextDniFocusLost

    }//GEN-LAST:event_jTextDniFocusLost

    private void jTextCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCiudadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCiudadActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextApellido;
    private javax.swing.JTextField jTextCiudad;
    private javax.swing.JTextField jTextDireccion;
    private javax.swing.JTextField jTextDni;
    private javax.swing.JTextField jTextNombre;
    private javax.swing.JTextField jTextTelefono;
    private javax.swing.JButton jbtBuscar;
    private javax.swing.JButton jbtSalir;
    private javax.swing.JLabel jlbIImagenLupa;
    // End of variables declaration//GEN-END:variables
}
